<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Fayaz" name="org.apache.atlas.seleniumtests.SearchPageTest" tests="8" failures="0" timestamp="30 Dec 2015 09:06:20 GMT" time="158.059" errors="2">
  <testcase name="testPageElements" time="11.100" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
  <testcase name="validateTagInSearchResult" time="34.812" classname="org.apache.atlas.seleniumtests.SearchPageTest">
    <error type="java.lang.AssertionError" message="Next Button enabled expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Next Button enabled expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.apache.atlas.seleniumtests.SearchPageTest.validateTagInSearchResult(SearchPageTest.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- validateTagInSearchResult -->
  <testcase name="validatePagination" time="39.846" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
  <testcase name="validateTableHeaders" time="1.812" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
  <testcase name="verifySearchResultNegative" time="17.678" classname="org.apache.atlas.seleniumtests.SearchPageTest">
    <error type="java.lang.AssertionError" message="No Result found message displayed expected [No Result found] but found [Error occurred during executing search query, error status code = 500, status text = Internal Server Error]">
      <![CDATA[java.lang.AssertionError: No Result found message displayed expected [No Result found] but found [Error occurred during executing search query, error status code = 500, status text = Internal Server Error]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.apache.atlas.seleniumtests.SearchPageTest.verifySearchResultNegative(SearchPageTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- verifySearchResultNegative -->
  <testcase name="validateTagSectionInSearchPage" time="0.204" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
  <testcase name="validateSearchResultCount" time="20.672" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
  <testcase name="searchTestMethod" time="31.935" classname="org.apache.atlas.seleniumtests.SearchPageTest"/>
</testsuite> <!-- org.apache.atlas.seleniumtests.SearchPageTest -->
